trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  Runtime: 'linux-musl-x64'

steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - task: DotNetCoreCLI@2
    name: Restore
    inputs:
      command: 'restore'
      projects: 'src/**/*.fsproj'
      arguments: '-r $(Runtime)'
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: 'build'
      configuration: 'Release'
      projects: 'src/**/*.fsproj'
      arguments: '-r $(Runtime)'
      publishWebProjects: false
  - task: DotNetCoreCLI@2
    name: Publish
    inputs:
      command: 'publish'
      configuration: 'Release'
      projects: 'src/**/Worker.fsproj'
      arguments: '-r $(Runtime) --sc --no-restore --no-build -p:PublishSingleFile=true -o $(Build.ArtifactStagingDirectory)'
      publishWebProjects: false
      zipAfterPublish: false
  - task: PublishBuildArtifacts@1
    name: Pack
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'